trigger:
  - master
  - main
  - staging
  - azure-pipelines

pool:
  vmImage: 'ubuntu-22.04'

jobs:
  - job: Build
    steps:
      # Normalizar finales de línea
      - task: PowerShell@2
        displayName: 'Normalize line endings'
        inputs:
          targetType: 'inline'
          script: |
            Get-ChildItem -Path "*.ps1", "*.psd1", "*.psm1", "*.nuspec" -Recurse | ForEach-Object {
              $content = [System.IO.File]::ReadAllText($_.FullName)
              $normalizedContent = $content -replace "`r`n", "`n"
              [System.IO.File]::WriteAllText($_.FullName, $normalizedContent)
              Write-Host "Normalized line endings in $($_.FullName)"
            }

      - task: NuGetCommand@2
        displayName: 'NuGet pack'
        inputs:
          command: pack
          packagesToPack: '*.nuspec'
      
      - task: NuGetCommand@2
        displayName: 'NuGet push'
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'nuget.org'