#!/bin/sh

# Create site. WARNING: use scape \ for $ character (example \$).
sudo bash -c 'cat > /etc/nginx/conf.d/helloWebApplication.conf' << EOF
server {
    listen        80;
    server_name   hello-web-application.example.com;
    location / {
        proxy_pass         http://localhost:5100;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host \$host;
        proxy_cache_bypass \$http_upgrade;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }
}
EOF

# Add DNS to localhost.
sudo bash -c 'cat >> /etc/hosts' << EOF

# Auto-generated by pipelines.
127.0.1.1 hello-web-application.example.com
EOF

# Start service
sudo service nginx restart

# Get active processes
ps -ef | grep nginx

# Wait some seconds
sleep 2
# Check that service is working
pwsh -command Invoke-WebRequest 'http://hello-web-application.example.com'